### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by fredzzhang** [fredzzhang/hicodet#6]
Error related to the new commit 4a42cabf0288b3a9e0a3e3e26d611a084d4539df
```
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [32,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
```
```
Traceback (most recent call last):
  File "train_detector.py", line 311, in <module>
    main(args)
  File "train_detector.py", line 290, in main
    engine(args.num_epochs)
  File "/home/fred/pkgs/pocket/pocket/core/engines.py", line 165, in __call__
    self._on_each_iteration()
  File "train_detector.py", line 39, in _on_each_iteration
    self._state.output = self._state.net(*self._state.inputs, targets=self._state.targets)
  File "/home/fred/miniconda3/envs/pocket/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fred/miniconda3/envs/pocket/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 51, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/fred/miniconda3/envs/pocket/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fred/miniconda3/envs/pocket/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 411, in forward
    boxes, scores = self.filter_proposals(proposals, objectness, images.image_sizes, num_anchors_per_level)
  File "/home/fred/miniconda3/envs/pocket/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 333, in filter_proposals
    keep = box_ops.remove_small_boxes(boxes, self.min_size)
  File "/home/fred/miniconda3/envs/pocket/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 75, in remove_small_boxes
    keep = keep.nonzero().squeeze(1)
RuntimeError: copy_if failed to synchronize: device-side assert triggered
```

The error appears to have been caused by incorrect indexing, as suggested by the error message from cuda. At the moment, it is suspected that flipping the bounding boxes resulted in certain box indices out of bounds.

**Comment by fredzzhang** [comment]
This error was caused by incorrect implementation of horizontal flipping for bounding boxes, see https://github.com/fredzzhang/pocket/issues/23. It should be fixed now.
